### ISSUE TITLE
Fix the extensive mode of the cipher test suite

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#294]
To be able to use the extensive mode, it is necessary to update `many-addresses.json` with all 1000 addresses (currently it only has 30). Additionally, a command must be added in `Makefile` for running the extensive mode.

**Comment by alexandermushinskiy** [comment]
@Senyoret1, the command is already exists in Makefile: `cipher-test`.
To run extensive mode, the value `CipherTestMode.QUICK` should be changed to `CipherTestMode.EXTENSIVE` in the `environment.cipher-test.ts` file. Do we need to have two separate commands (for extensive and quick modes)?

**Comment by Senyoret1** [comment]
@alexandermushinskiy, yes, we need another command. That would help not only to run the extensive tests more easily, but it also would make it easier to read the code in the future, in case it should be reviewed by someone who is not aware of how to configure the tests.

**Comment by alexandermushinskiy** [comment]
Please be informed that issue is implemented.
`--cipher extensive` or `--cipher quick` arguments are used to run Cipher tests in different modes.

Just want to mention there is no check if user specify incorrect value of cipher mode, for example `--cipher bla-bla-bla`. In a such cases the `quick` mode will be used.
