### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by mahansky** [skycoin/skycoin-web#400]
- use font-weight: 400 when using Skycoin Regular font (styles.scss)
- format coin hours / sky amount in header and wallets
- transaction detail modal has white background
- qr code modal have inconsistent margin/padding, also the button to copy address is different than others
- seed warning in create wallet modal should be moved a bit closer to seed input
- (?) there is a "cancel" button in every modal which is a bit excessive, when you can cancel it by clicking the "x" in header or outside of it
- fix transaction history (address alignment, multiple addresses)

**Comment by Senyoret1** [comment]
There are some things that are not completely clear to me:

- What kind of format would be applied to coin hours/sky? In the explorer a change was made to the way of showing the amounts, which could also help improve the readability in the wallet, but I do not know if you mean something like that: https://github.com/skycoin/skycoin-explorer/pull/206

- I think the QR modal should be the same as the one on the desktop wallet (I mean using the same code), although the copy button can be added, what do you think?

- I think that the "cancel" buttons should not be removed because having one is a standard. The confirmation messages on the operating systems also have a button to close the modal and a cancel button. Removing the button could be bad for the UX.

**Comment by mahansky** [comment]
Format numbers with the `| number` directive so it's more readable
QR modal - ok, image will fill the content area and there will be the address and copy button (maybe even separate them from the image)
![screen shot 2018-07-02 at 16 46 02](https://user-images.githubusercontent.com/1536298/42170642-6e7dd960-7e17-11e8-89aa-7021ce168dd3.png)

**Comment by Senyoret1** [comment]
It looks good, the separator is consistent with the rest of the design. Maybe a little more margin would be good.
