### ISSUE TITLE
Cleanup repeated functionality in code

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-web#53]

**Comment by samuelvisscher** [comment]
The hired programmers put duplicate code in the repository which will need to be removed, and the repository should be brought in sync with Skycoin Core wallet code

**Comment by alexandermushinskiy** [comment]
@samuelvisscher, could you verify please what should be sync:
- Wallets page:
	•	Copy button near the wallet address in the Core wallet.
	•	View QR Code modal window in the Web wallet.
		Which one to use for sync project?
- ApiService:
	getting CSRF token for POST requests does not exist in the Web wallet. We will be added.
- WalletService:
	remove legacy and unused code in the Web wallet.
- NetworkService:
	it is never used in the Web wallet, we are going to delete it.

**Comment by gz-c** [comment]
@Senyoret1 can you help with @alexandermushinskiy 's question

**Comment by Senyoret1** [comment]
Hi,

In fact, the things that need to be synchronized are constantly changing, because the desktop wallet is constantly changing. For example, the dialog for creating a new wallet and the wizard will change with this pr: https://github.com/skycoin/skycoin/pull/1187

With respect to the indicated points, it is necessary to update the copy button and also various parts related to qr codes (there were changes in https://github.com/skycoin/skycoin/pull/1185). Also, I suppose that the CSRF token must be requested and used, because otherwise the node will reject the post requests. It is already implemented in the desktop wallet.

The unused code on WalletService must be deleted, but it is necessary to be careful, because there are parts below the “Legacy” comment that apparently are still in use. NetworkService is only useful in the desktop wallet, so there should be no problem in deleting it.

Additionally, surely there are other things to change, so I will be checking the code and adding issues with things that should be modified.

**Comment by gz-c** [comment]
CSRF is irrelevant to the web wallet. The web wallet should not be making any POST requests and the backend node that supports the web wallet would have all of those APIs disabled and be run as a read-only node.

**Comment by alexandermushinskiy** [comment]
@gz-c, here is a list of methods which are used post requests:
- NetworkService - will be removed as @Senyoret1 mentioned above;
- WalletService -> postTransaction(): using for sending skycoins, API call is ../api/injectTransaction;
- PurchaseService -> generate(): using for generate deposit address, API call is ../api/bind;

Could you please approve that mentioned functionality should not be available in web wallet and have to be removed?

**Comment by Senyoret1** [comment]
`injectTransaction` is just the call I was tinking about. As far as I know, it is necessary to continue using it. As for `PurchaseService`, I don't know what the state of that part is or if it is planned to be activated soon, but it is connected to the teller, not the node, so I think the token is not necessary.
