### ISSUE TITLE
Wallets seeds and private keys are in memory all the time

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin-web#549]
The `seed`, `next_seed` and `private key` of wallets are in memory all the time when `environment.production` is true.  We should keep the alive time of these sensitive data as short as possible. 

In none production mode, refreshing will wipe out the sensitive data and load the wallets we created previously, but the wallets we created later will keep the sensitive data in memory before we refreshing.

**Comment by Senyoret1** [comment]
It was designed that way to make it work like MyEtherWallet. The idea is that the user will have to enter the seed to load the wallet, but will not need to enter it again to send a transaction (but just while the browser/tab is not closed/refeshed).

Removing the sensitive data just after using it would negatively affect the UX, specially because the current crypto library is very slow. However, if you think I should get rid of any sensitive data as soon as possible, it could be done.

**Comment by Senyoret1** [comment]
@mahansky

**Comment by mahansky** [comment]
The sensitive info will be exposed at some point, one way or the other. From what I know, this is how most of the web wallets work, making the overall UX better.

**Comment by gz-c** [comment]
It needs to stay in memory because there is no backend to retain the secrets.  We keep it out of memory in the desktop wallet because the backend retains the secrets instead.  But, when the browser page is closed, the secrets are all wiped.
