### ISSUE TITLE
Remove the sensitive data in html file

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin-web#552]
In the `create-wallet-form.component.html` file,  we use code
```html
 [ngClass]="{ '-expand':form.get('confirm_seed').value === form.get('seed').value }"
```
to check if the seed and confirmed_seed are matched, instead of using the sensitive data to do the comparing in html file, we should call a function from `.ts` file to check.

Also we should avoid to use a `wallet` with sensitive data in html file.

**Comment by Senyoret1** [comment]
In Agular, html files are converted to javascript files when compiling, as features like the one you mention are not possible with plain html. Because of that, the wallet objet is not really added in the final html, but it is just in a javascript code that takes care of updating the DOM when needed.

Taking that into account, having the value in the html template should be as safe as having it in a ts class. I checked a bit in the Internet, just in case, and could not find info about that being a security risk. However, I may be wrong, do you have in mind something in particular that could cause problems? I ask just because the change is indeed viable, but, if the change is made in all places where we could have sensitive information, it could require complicating the code in a way that I think I would like to avoid if possible.

**Comment by Senyoret1** [comment]
@mahansky

**Comment by mahansky** [comment]
@Senyoret1 is right, it shouldn't make a difference having it in template file or in ts.
